# Usa una imagen base de Python
FROM python:3.9-slim

# Instala GCC y otras herramientas necesarias para la compilación
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo requirements.txt y los archivos del proyecto al contenedor
COPY requirements.txt /app/
COPY . /app/

# Instala las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 8501 para Streamlit
EXPOSE 8501

# Comando para ejecutar la aplicación Streamlit
CMD ["streamlit", "run", "inferencia.py"]
